name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t duck333/runpod-worker-comfy-docker:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push duck333/runpod-worker-comfy-docker:latest
